version: '3.8'
services:
  app:
    container_name: test-app
    restart: always
    build: ./
    # command: ./wait-for-postgres.sh db ./app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=testtask
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testtask